name: chromatin-deconvolution
channels:
  - defaults
dependencies:
  - python=3.8
  - matplotlib
  - jupyter
  - pandas
  - numpy
  - scikit-learn
  - statsmodels
  - pytables
  - pip
  - pip:
    - goatools==1.4.12
    - cvxpy
    - pysam
    - PyWavelets
    - Mosek
    - kneed==0.8.5

