all_models = {'DIFF_G1' ...
	'RDG1'...
	'RCG1'...
	'NORMAL' ...
	'SRDG1' ...
	'SRCG1' ...
	'SCG1R' ...
	'SDG1R' ...
	'SCG1RF' ...
	'SCG1DG1' ...
	'RG1' ...
	'DG1' ...
};

dir = 'all_model_pdf';

alpha = [26 27];
datatype = 'joint';

for i=1:length(all_models);
	cur_model = all_models{i};
	drawBranch(cur_model, datatype, alpha);
	
	fig = strcat(dir, '/', cur_model, '.pdf');
%	set(gcf, 'PaperUnits', 'inches');
%	set(gcf, 'PaperSize', [7 4]);
%	saveas(gcf, fig, 'pdf');
%	print(gcf, '-dpsc', fig);
	close;
end

