function [model] = parseModelType(model)

modeltype = upper(model.modeltype);

all_models = {'1.1.1' 'CDG1', ...
	'1.1.1.1' 'DG1LCG1'...
	'1.1.1.2' 'DG1ECG1'...
	'1.1.2.1' 'RCD'...
	'1.2.1' 'RCDG1'...
	'1.2.1.1' 'RG1LCG1'...
	'1.2.1.2' 'RG1ECG1'...
	'1.2.1.3' 'RG1EDG1'...
	'1.2.1.4' 'RG1LDG1'...
	'1.2.2' 'RCG1'...
	'1.2.3' 'R.DG1'...
	'1' 'ROOT'...
};

idx = strmatch(modeltype, all_models, 'exact');

if length(idx) > 0;
	if rem(idx,2) == 0
		model.modelprefix = all_models{idx-1};
		disp(sprintf('Standard modeltype: %s', model.prefix));
	else
		model.modelprefix = modeltype;
		model.modeltype = all_models{idx+1};
	end
else
	error('MODEL type error');
end

return;
